In [1]:
import numpy as np

In [3]:
# membuat vektor
a = np.array([1,2,3,4,5])
b = np.array([1.2, 3.4, 3.4, 2.3])
print(a)
print(b)

[1 2 3 4 5]
[1.2 3.4 3.4 2.3]


In [4]:
# membuat vector dengan range
# argument ketiga => step
c = np.arange(1,10,2)
print(c)

[1 3 5 7 9]


In [5]:
# membuat linspace
# parameter ketiga => membagi sebanyak 4 bagian
d = np.linspace(1,10,4)
print(d)

[ 1.  4.  7. 10.]


In [6]:
# array multidimensi / matrix
# baris pertama = 12345
# baris kedua = 678910
e = np.array([ (1,2,3,4,5),(6,7,8,9,10)])
print(e)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [7]:
# pembuktian bahwa itu benar2 matrix, tambah 1 (skalar)
e += 1
print(e)

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]]


In [8]:
# matrix kosong / nilai nol
# 5 => len
f = np.zeros(5)
print(f)

[0. 0. 0. 0. 0.]


In [11]:
# matrix 5 x 5
g = np.zeros((5,5))
print(g)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
# matrix 1
h = np.ones(5)
print(h)

[1. 1. 1. 1. 1.]


In [15]:
print(i)
i = np.ones((5,5))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
# matrix identitas (diagonal)
# 5 x 5
j = np.identity(5)
print(j)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
j2 = np.eye(5)
print(j2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
