In [1]:
import numpy as np

In [8]:
a = [1,2,3,4,5]
b = [6,7,8,9,10]

anp = np.array([1,2,3,4,5])
bnp = np.array([6,7,8,9,10])

# penjumlahan
# concat
hasil = a + b
print(hasil)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [9]:
# elementwise operation
# benar2 dijumlahkan
hasil = anp + bnp
print(hasil)

[ 7  9 11 13 15]


In [10]:
# pengurangan
hasil = anp - bnp
print(hasil)

[-5 -5 -5 -5 -5]


In [12]:
# perkalian
hasil = anp * bnp
print(hasil)

[ 6 14 24 36 50]


In [13]:
# pembagian
hasil = anp / bnp
print(hasil)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [14]:
# kuadrat
hasil = anp** 2
print(hasil)

[ 1  4  9 16 25]


In [15]:
# multidimensi
cnp = np.array(( [1,2,3], [4,5,6] ))
dnp = np.array(( [7,8,9], [-1,-4,-2] ))
hasil = cnp + dnp
print(hasil)

[[ 8 10 12]
 [ 3  1  4]]


In [16]:
# semua operasi matematika di numpy adalah element wise operation
# perkalian tidak seperti matrix
hasil = cnp * dnp
print(hasil)

[[  7  16  27]
 [ -4 -20 -12]]
