In [1]:
import numpy as np

In [27]:
a = np.array(([1,4],
              [4,5]))

b = np.ones([2,2])

print('matrix a : \n', a)
print('matrix b : \n', b)

matrix a : 
 [[1 2 3 4]
 [4 6 9 5]]
matrix b : 
 [[1.]
 [1.]
 [1.]
 [1.]]


In [28]:
# perkalian matrix
c1 = np.dot(a,b)
c2 = a.dot(b)
print(c1)
print(c2)

[[10.]
 [24.]]
[[10.]
 [24.]]
